all: part1 part2 part3 part4 part5

part1: part1.cpp
	g++ -o part1.exe part1.cpp

part2: part2.cpp
	g++ -o part2.exe part2.cpp

part3: part3.cpp
	g++ -o part3.exe part3.cpp
part4: part4.cpp
	g++ -o part4.exe part4.cpp
part5: part5.cpp
	g++ -o part5.exe part5.cpp
clean:
	-rm *.o *.exe
